.job-template: &job
  image: "hatsoftwares/sympa-perl-${CI_JOB_NAME}:latest"
  retry: 2
  before_script:
    - . ~/.bash_profile
    - perl -v
  script:
    - for i in lib/*.pl lib/MHonArc/*.pm lib/MHonArc/*/*.pm; do perl -Ilib -c $i; done
    - perl Makefile.PL
    - make
    - make install
    - make tardist
    - cpanm -L local MHonArc-*.tar.gz
    - make clean

"5.10":
  <<: *job
"5.12":
  <<: *job
"5.14":
  <<: *job
"5.16":
  <<: *job
"5.18":
  <<: *job
"5.20":
  <<: *job
"5.22":
  <<: *job
"5.24":
  <<: *job
"5.26":
  <<: *job
"5.28":
  <<: *job
"5.30":
  <<: *job
